# Base

substitutions:
  name: guition-p4-70
  friendly_name: Guition P4 70

## Modular version Main P4

## SETTINGS ######################################################################################################################################

  imagewidth:  "400"
  imageheight: "600"

  screenwidth:  "1024"
  screenheight: "600"
  rotate_display: "0"

  startup_sound: "Home_Connected" # (options are: available, Home_Connected, Home_Connected_Male, Computer_Ready)
  clock_background_image: "chip" # (options are: clock, hacker, mission, starrysky, waves, tron, chip)
  imagemodel: "Gwen" # options are: Gwen

# USE ONLINE OR LOCAL MODEL AND WALLPAPER IMAGES, IMAGES SHOULD BE PLACED IN homeassistant/www/images/
#  imagepath: "https://github.com/sesarhayo-sys/matrix-esphome/raw/main/images"
  imagepath: "http://homeassistant.local:8123/local/images/"

## PRESENCE / MOTION SENSORS ########## IF NOT USING THESE LEAVE THEM ALONE, SCRIPT WILL BREAK WITHOUT ###########################################

  sensor1_entity: "binary_sensor.8266_presense_2_presence"
  light1_entity: "light.livingroom_all_lights"
  sensor1_label: "Tech Room"

  sensor2_entity: "binary_sensor.esp32s3_1_presence"
  light2_entity: "light.kitchen_lights"
  sensor2_label: "Kitchen"

  sensor3_entity: "binary_sensor.esphome_web_1911bf_presence"
  light3_entity: "light.mom_s_room"
  sensor3_label: "Living Room"

  sensor4_entity: "binary_sensor.notifier_2_presence"
  light4_entity: "light.hue_toilet_light_light"
  sensor4_label: "Toilet"

  sensor5_entity: "binary_sensor.8266_presense_presence"
  light5_entity: "switch.nedis_smart_plug_tasmota1"
  sensor5_label: "Hall"


  weather_entity: "weather.forecast_home"

##################################################################################################################################################

  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

esp32:
  board: esp32-p4-evboard
  flash_size: 16Mb
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: y

psram:
  speed: 200MHz

esp_ldo:
  - channel: 3
    voltage: 2.5V

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

logger:
  level: DEBUG

### USE MODULES FROM GITHUB (default) ############################################################################################################

#packages:
#  core:
#    url: https://github.com/sesarhayo-sys/matrix-esphome.git
#    ref: main
#    refresh: 0s
#    files:
#      - matrix-esphome/core.yaml
#  hardware:
#    url: https://github.com/sesarhayo-sys/matrix-esphome.git
#    ref: main
#    refresh: 0s
#    files:
#      - matrix-esphome/hardware/guition_7_0.yaml

### USE LOCAL MODULES (read description https://github.com/sesarhayo-sys/matrix-esphome/blob/main/README.md) #######

packages: # Local
  core: !include matrix-esphome/core.yaml
  hardware: !include matrix-esphome/hardware/guition_7_0.yaml
  voice: !include matrix-esphome/voice/assistant_overlay.yaml

# --- CLOCKS PACKAGE -----------------------------------------------------------
#packages:
  clocks: !include matrix-esphome/clocks-standard.yaml
## ENABLE / DISABLE WAKE WORDS ## IF LOW ON MEMORY, USE LESS WAKE WORDS ##########################################################################

micro_wake_word:
  id: mww
  models:
    - okay_nabu
    - hey_jarvis
    - alexa
#    - hey_mycroft
#    - model: https://raw.githubusercontent.com/sesarhayo-sys/matrix-esphome/refs/heads/main/mww/models/v2/hey_sarah.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/computer/computer.json
#    - model: https://raw.githubusercontent.com/JohnnyPrimus/Custom_V2_MicroWakeWords/refs/heads/main/models/hey_friday/hey_friday.json
#    - model: https://github.com/kahrendt/microWakeWord/releases/download/okay_nabu_20241226.3/okay_nabu.json
#    - model: https://raw.githubusercontent.com/formatBCE/Respeaker-Lite-ESPHome-integration/refs/heads/main/microwakeword/models/v2/kenobi.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/choo_choo_homie.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_home_assistant.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/hey_peppa_pig.json
#    - model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/experiments/okay_computer.json

##################################################################################################################################################